name = "TreatmentTrajectories"
uuid = "692400ee-4f07-4849-b443-1c0d23e91053"
version = "0.1.0"
authors = ["Simon Steiger"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DrugInterface = "ecbac44d-373e-48a5-bcbb-08f349367545"

[compat]
DrugInterface = "0.2.0"
julia = "1.11"

[sources]
DrugInterface = {url = "https://github.com/simonsteiger/DrugInterface.jl"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
