name: CI

on:
  push:
    branches:
      - main
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

# Cancel existing tests on the same PR if a new commit is added to a pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/main' }}


jobs:
  test:
    runs-on: ${{ matrix.runner.os }}
    strategy:
      fail-fast: false

      matrix:
        runner:
          # Ubuntu
          - version: '1'
            os: ubuntu-latest
          # Windows
          - version: '1'
            os: windows-latest
          # macOS
          - version: '1'
            os: macos-latest
          # Minimum supported version
          - version: 'min'
            os: ubuntu-latest
          # 1.11
          - version: '1.11'
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # 3.0.2
        with:
          version: ${{ matrix.runner.version }}

      - uses: julia-actions/cache@a45e8fa8be21c18a06b7177052533149e61e9b38 # 3.1.0

      - uses: julia-actions/julia-runtest@d60b785c6f2bdf4ebfb18b2b6f7d93b7dfb0efe3 # 1.11.4
        env:
          # Only run Aqua tests on latest version
          AQUA: ${{ matrix.runner.version == '1' && 'true' || 'false' }}
